### ISSUE TITLE
Are you going to make it OpenSource ?

### ISSUE THREAD

**Issue by raphaelamorim** [lfcnassif/IPED#1]
I'd read this:

http://m.folha.uol.com.br/poder/2017/01/1846272-neo-volume-de-dados-da-lava-jato-forca-pf-a-criar-novo-sistema.shtml

**Comment by raphaelamorim** [comment]
I've also noticed you'd forked the sleuth kit, are you following the license restrictions?

**Comment by lfcnassif** [comment]
Hi Raphael,

IPED currently is open sourced, licensed under GNU GPL 3. The github site
is not ready yet, but when distributed it goes with the sources.

I am on vacation and as soon as I come back I Will re-check the sleuthkit
license to see if I missed something.

Do you speak portuguese?

Regards,
Luis Nassif


Em 2 de jan de 2017 4:10 PM, "Raphael Amorim" <notifications@github.com>
escreveu:

I've also noticed you'd forked the sleuth kit, are you following the
license restrictions?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lfcnassif/IPED/issues/1#issuecomment-270004038>, or mute
the thread

**Comment by felipemnp** [comment]
Luis, tudo bem? Espero que tenha aproveitado as merecidas férias...
Alguma previsão para liberação do IPED por aqui? Ele está disponível (mesmo que em formato executável) em algum outro site?
Desde já muito obrigado,
Felipe Mendel

**Comment by lfcnassif** [comment]
Olá Felipe, desculpe a demora.
Estamos discutindo uma possível alteração no licenciamento. Até definirmos, a publicação por aqui está suspensa, como deve ter percebido.

**Comment by lfcnassif** [comment]
After some study, we discovered that Sleuthkit licenses IBM Public License and Common Public License are incompatible with GNU GPL 3 on both directions. So in version 3.13 of IPED (not public available currently), we removed all GPL3 dependencies and added an exception to IPED GPL3 license to allow linking IPED with The Sleuthkit. So I am closing this as resolved.

**Comment by lfcnassif** [comment]
Code finally published. Any contributions will be welcomed.
