### ISSUE TITLE
Problem importing NSRL

### ISSUE THREAD

**Issue by GRCWill** [lfcnassif/IPED#12]
Boa tarde lfcnassif

Estou com problemas para importar o NSLR no IPED, no meu caso nem chega a iniciar a importação. aparece o erro: 
"ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console."
Poderia dar uma ajuda por favor? 
Obrigado!

**Comment by lfcnassif** [comment]
I identified a problem with NSRL importing, not as you described because it throws an error. What is the iped and NSRL version you are using?
I already fixed the bug I identified in master branch. Will release another beta english version after Christmas, but you can try to compile master before.
Please reply in english for better understanding by others.

**Comment by GRCWill** [comment]
Thanks for answering!

We are using IPED version 3.15.16,
regarding NRSL we tried the latest version and some previous ones:
2.49, 2.51, but the same error occurred,
we are trying to run on Windows 10.

**Comment by lfcnassif** [comment]
Please, try the last 3.17-rc2 beta release, just uploaded in releases section.

**Comment by lfcnassif** [comment]
A related problem was identified and fixed. Can't reproduce this. Please reopen if you have problems with version 3.17-rc3.

**Comment by fabriciossouza13** [comment]
Boa tarde.

Estou tentando realizar o import do NSRL para o IPED 4.0.0 e, ao que parece, não há o parâmetro -importkff nesta versão. Executei o comando iped.exe --help e não vi o parâmetro disponível.

Como poderia realizar este import?
